global:
  nodeSelector: {}
  affinity: {}
  tolerations: {}
  storageClass: ""

nginxReplicaCount: 1

phpReplicaCount: 1

metadata:
  labels:
    environment: dev

image:
  repository: bahmni
  name: crater-atomfeed
  tag: latest
  

service:
  type: ClusterIP
  port: 80

config:
  CRATER_ATOMFEED_DB_HOST: ""
  CRATER_URL: "http://crater-nginx"
  CRATER_ATOMFEED_DB_NAME: "crater_atomfeed"
  CRATER_ATOMFEED_DB_PORT: "3306"
  OPENMRS_HOST: "openmrs"
  OPENMRS_PORT: "8080"
     

secrets:
  OPENMRS_ATOMFEED_USER: ""
  OPENMRS_ATOMFEED_PASSWORD: ""
  CRATER_USERNAME: ""
  CRATER_PASSWORD: ""
  CRATER_ATOMFEED_DB_USERNAME: ""
  CRATER_ATOMFEED_DB_PASSWORD: ""

autoscaling:
  enabled: false

nodeSelector: {}
affinity: {}
tolerations: {}

volumes:
  craterAppData:
    capacity: 8Gi
